name: Deploy API Gateway to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PROD_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2 Prod
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@<PROD_IP> << 'EOF'
            cd api-gateway
            git pull origin main
            docker compose down
            docker compose up -d --build
          EOF
