name: Deploy API Gateway to QA

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_QA_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2 QA
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@<QA_IP> << 'EOF'
            cd api-gateway
            git pull origin qa
            docker compose down
            docker compose up -d --build
